### ISSUE TITLE
Error: [$compile:ctreq] Controller 'select', required by directive 'ngOptions', can't be found!

### ISSUE THREAD

**Issue by iesen** [tamtakoe/oi.select#10]
This error appears in console.

ng-options directive requires a select element, could this be ignored if we use another attribute name other than ng-options

**Comment by fagnercarvalho** [comment]
I got the same problem as well. It seems that if you are using Angular 1.4 >= this will happen. Moreover, the best directive to handle dropdown values is the ng-option, so I dont think we can change that.
Weirdly I getting this error only after add more than one multiselect directive in my view.

**Comment by bfolder** [comment]
Yes, one could use something like 'oi-option' instead of 'ng-option' to get rid of that error. Changes the interface though.

**Comment by fagnercarvalho** [comment]
Oh, this can be done too. 
I'm a very new Angular user, so sorry for don't consider this alternative.

**Comment by Serginho** [comment]
Yes, I think there's no choise. Interface should be changed.

**Comment by bfolder** [comment]
I'm adding a 0.1.8 tag on my fork, and include it as dependency as long as this repo is not being updated.

**Comment by tamtakoe** [comment]
I fix it in version 0.2.0.

**Comment by LeonSkrilec** [comment]
Actually i got this error when placing ng-options on a non select DOM element. Might be helpfull to someone debugging.

**Comment by hustshawn** [comment]
Hi, anyone fixed the issue?

**Comment by rohtashsethi** [comment]
We have to use bs-options instead of ng-options. AngularStrap provide a directive bs-options for TypeAhead.
http://mgcrea.github.io/angular-strap/#typeaheads
