### ISSUE TITLE
when use mse input something, then couldn't select option

### ISSUE THREAD

**Issue by aizigao** [tamtakoe/oi.select#106]
- I find a bug blow chrome 53, chrome 53 is work fine
- when I use mse in embedded coding model ， then couldn't select options
  eq:
  ![001](https://cloud.githubusercontent.com/assets/14126445/18778706/44e4a7f4-81a8-11e6-8abd-344064485281.gif)

you can see it before became chinese characters was alphabets , 
- this bug just in blow chrome 53, when I not use embedded coding model mse , it also work well
  ![002](https://cloud.githubusercontent.com/assets/14126445/18778760/7adacc12-81a8-11e6-9b94-33fa57e73e09.gif)

I think it trigger options's disabled ,
**so , can you tell me, how to forbed disabled**

**Comment by weixiangzhe** [comment]
ok, I had seen more  about this problem, when I **focus <input > again ** options can selected ,
![003](https://cloud.githubusercontent.com/assets/14126445/18778896/4665e484-81a9-11e6-9514-0b464590e8b5.gif)


oh.no...

**Comment by weixiangzhe** [comment]
##HI! , I think have solved this bug !!!##
 when I use  mse in embed model   ,`getMatches()` function trigger twice , and first times the `filteredOutput` is empty and the second times `filteredOutput` is not.
![gif](https://cloud.githubusercontent.com/assets/14126445/18820854/bb2eb6de-83d3-11e6-8154-756f50063d44.gif)

I find blow code 
```js
console.info("filteredOutput:  ",  filteredOutput ); 
if (!filteredOutput.length) {

    scope.isEmptyList = true;

    if (listPlaceholder) {
        var context = {};

        displayFn.assign(context, listPlaceholder);
        filteredOutput = [context[valueName]]
    }
}
```

so , I add `else` to fix it
```js
//add element with placeholder to empty list
console.info("filteredOutput:  ",  filteredOutput ); 
if (!filteredOutput.length) {

    scope.isEmptyList = true;

    if (listPlaceholder) {
        var context = {};

        displayFn.assign(context, listPlaceholder);
        filteredOutput = [context[valueName]]
    }
}else{
    scope.isEmptyList = false
}
```

then in second times  ,    `scope.isEmptyList` become false again
