### ISSUE TITLE
Error loading multiple dropdowns in same view?

### ISSUE THREAD

**Issue by fagnercarvalho** [tamtakoe/oi.select#11]
I getting a error every time I try to load more than one dropdown in my view. 
Why this is happening exactly?

![multiple-dropdowns](https://cloud.githubusercontent.com/assets/817867/8401138/b0f1b642-1e00-11e5-9c5a-107f4fe3ff8b.png)

Here is the code related to print above:
```
<div class="col-xs-6">
	<label class="control-label">Test1</label>
	<oi-multiselect 
					ng-options="testOne.Name for testOne in testOneDrop track by testOne.Id" 
					ng-model="testOne" 
					multiple></oi-multiselect>
</div>
<div class="col-xs-6">
	<label class="control-label">Test2</label>
	<oi-multiselect
					ng-options="testTwo.Name for testTwo in testTwoDrop track by testTwo.Id" 
					ng-model="testTwo" 
					multiple></oi-multiselect>       
</div>
```

**Comment by bfolder** [comment]
I'm having no problems using more than one instance. Might be the rest of your code.

**Comment by tamtakoe** [comment]
@fagnercarvalho I have no problem. Write example in http://plnkr.co, please

**Comment by tamtakoe** [comment]
I think it works correctly in 0.2.5
