### ISSUE TITLE
Call function in ng-options / io-options

### ISSUE THREAD

**Issue by bagofjuice** [tamtakoe/oi.select#15]
I would like to call a function within the ng-options parameter.  This works with regular select but not with ng-multiselect / io-select:

    ng-options="item as myGeTextMethod(item) for item in items"

**Comment by tamtakoe** [comment]
@bagofjuice ng-options doesn't work since 0.2.0 (it is incompatible with angular 1.4+). Use oi-options

**Comment by bagofjuice** [comment]
Ok fine, function calls within the renamed oi-options do not work either.

**Comment by tamtakoe** [comment]
I fix it in master. I publish a new release after the test

**Comment by bagofjuice** [comment]
This works, thanks.

However here's a follow up bug: https://github.com/tamtakoe/oi.select/issues/16

**Comment by tamtakoe** [comment]
Thank! I fixed it in version 0.2.1
