### ISSUE TITLE
Order of selected items in multi select list

### ISSUE THREAD

**Issue by bagofjuice** [tamtakoe/oi.select#16]
When using 'select as' the selected items don't show in the order they were added.

http://plnkr.co/edit/nT5ElcG3ma6BoL5UoZyb?p=preview

**Comment by tamtakoe** [comment]
I fixed it in version 0.2.1

**Comment by bagofjuice** [comment]
This works, thanks.  However 'bower install' doesn't contain the updates.

**Comment by tamtakoe** [comment]
Try to remove the plug-in, clean the bower cache (`bower cache clean`) and re-install

**Comment by bagofjuice** [comment]
I had to clean the cache, thanks.
