### ISSUE TITLE
Hitting enter to select a value from a dropdown for a multiple select causes the form to be submitted

### ISSUE THREAD

**Issue by simong** [tamtakoe/oi.select#21]
I think this is due to changing from keydown to keyup in [template/select/template.html](https://github.com/tamtakoe/oi.select/commit/c42cfb1da3ca77deee07e26a87477ca045031461#diff-57c8853241d4ccbe3efef0e6ccc8efc9R13)

**Comment by tamtakoe** [comment]
@simong I returned keyDown and use keyUp only for backspace in 0.2.5. It should work correct
