### ISSUE TITLE
tabindex attribute isn't being removed correctly

### ISSUE THREAD

**Issue by simong** [tamtakoe/oi.select#25]
First off, thank you for adding the tabindex attribute, it's exactly what we need.

There's a small bug however. When add `tabindex="0"` to the `oi-select` element and step through the code the input's field tabindex correctly gets its tabindex attribute set to 0 and the tabindex attribute on the `oi-select` element gets removed. However when I stop stepping through and just let the script resume it looks like `tabindex="0"` attribute added again to the `oi-select` field.

When you have the following source:
```
<input type="text" name="title" tabindex="1" /> <br />
<oi-multiselect tabindex="2" ... />
<input type="submit"  tabindex="3" />
```

it ends up (after full initialization) as:
```
<input type="text" name="title" tabindex="1" /> <br />
<oi-multiselect tabindex="0">
   ...
   <input type="text" tabindex="2" />
   ...
</oi-multiselect>
<input type="submit"  tabindex="3" />
```

So when you tab from the title field you end up focussing the oi-multiselect element and NOT the input field in the oi-multiselect

**Comment by tamtakoe** [comment]
I try your case in Windows Chrome. It work correct. Focus always stops to the input field. In IE and FF tabindex doesn't work. I think, how to fix it
