### ISSUE TITLE
Using function to translate selection texts

### ISSUE THREAD

**Issue by Hypocrite** [tamtakoe/oi.select#27]
Hi,

I am using the following module to translate our application:
https://angular-gettext.rocketeer.be/

It seems to work in all other cases but when I try to translate ng-options for oi.select.

For example this works fine:
```
<select class="form-control form-input-select" ng-model="testData.test" ng-options="translate(t.name) group by translate(t.group) for t in trainings | orderBy:['group','name']" ng-change="selectedTest(testData.test)">
<option value="" translate>-- Select test --</option>
</select>
```

But this fails to print the translated text but prints an empty list item:
```
<oi-multiselect
ng-model="selectedTests" 
ng-options="translate(item.name) group by translate(item.group) for (key, item) in tests"
name="tests"
multiple
placeholder="{{'Add new'|translate}}"
required
></oi-multiselect>
```

I don't get any errors in console.log.

**Comment by tamtakoe** [comment]
I will consider this case. You can try to use translate function into `searchFilter`, `dropdownFilter` and `listFilter`

**Comment by Hypocrite** [comment]
Hi,

That sounds like a good solution.

Could you give an example how can I run both the group title and item title through the function?

I think your examples only covered the item filtering.

**Comment by tamtakoe** [comment]
You can see examples on http://tamtakoe.github.io/oi.select/#/select/#customization

You need `dropdownFilter` for translate each element in dropdown list and `searchFilter` — in select area.

```html
<oi-select oi-options="item.name for item in shopArr track by item.id"
                ng-model="bundle"
                multiple
                oi-select-options="{
                    searchFilter: 'translateFilter',
                    dropdownFilter: 'translateFilter'
                }"></oi-select>
```

```js
.filter('translateFilter', ['$translate', function($translate) {
    return function(label) {
        return $translate(label);
    };
}])
```

**Comment by Hypocrite** [comment]
This seems to work for translation the option labels but it does not translate the group labels.

**Comment by tamtakoe** [comment]
You can use `listFilter`

```js
.filter('listFilter', function(translate) {
    return function (list, query, getLabel) {
        return translate(list);
    }
});
```
Pseudo realisation of translate function

```js
function translate(list)
    return list.map(function(item) {
        return {
            id: item.id,
            name: item.name,
            category: $translate(item.category), //group name
        }
    })
}
```

**Comment by tamtakoe** [comment]
Make, please, example with native `select` in plnker. I can't make the example to work fine

**Comment by Hypocrite** [comment]
Here is a working Plunker with native select with grouped items and translates from English to Finnish: http://plnkr.co/Z5fur8X5dKABOtPv8ctV?p=preview

**Comment by tamtakoe** [comment]
I began to fix your case, but I saw that it worked well
http://plnkr.co/edit/Lbr22KJ7X4TCsSUFK03v?p=preview

P.S. There is mistake in your example - duplicate keys in `gettextCatalog.setStrings`

**Comment by Hypocrite** [comment]
I just updaded to 0.2.9 and it seems to work now without problems.

Don't know what the issue was before.

Thanks for using the time to solve the problem.

**Comment by tamtakoe** [comment]
No problem :-) You can update to 0.2.10 now
