### ISSUE TITLE
Issues with version 0.2.8

### ISSUE THREAD

**Issue by Hypocrite** [tamtakoe/oi.select#28]
I just upgraded from oi.multiselect 0.1.7 to oi.select 0.2.8.

I noticed that there are a few weird things in the version.

1. When selecting multiple values, the select box closes after each click which did not happen earlier. This makes selecting multiple values very slow.

2. It seems that it does not register clicks everytime. I was able to reproduce this also with the demo http://tamtakoe.github.io/oi.select/#/select/#multiple with Google Chrome. When I click on different values I randomly have to click twice to add the selection.

**Comment by tamtakoe** [comment]
I'll fix it in the new version in a few hours

**Comment by tamtakoe** [comment]
fixed in 0.2.9

**Comment by Hypocrite** [comment]
The second problem seems to be fixed with 0.2.9 but it still closes the select box after each click which makes selecting items slower than before.

**Comment by tamtakoe** [comment]
@Hypocrite I fixed it in 0.2.9 immediately after publish this tag. Maybe you have installed it before my changes was applyed. Try 0.2.10

**Comment by Hypocrite** [comment]
@tamtakoe I tested it also with 0.2.10 and it still keeps closing the select box after selecting one option.

Happens also in here:
http://plnkr.co/edit/LnntLUdrAfz0DDlCGtGv?p=preview

Testing with Google Chrome.

**Comment by tamtakoe** [comment]
If I understand correctly... Dropdown closes after selecting an option. It is native select behaviour. Maybe you need option `closeList`? http://plnkr.co/edit/fI0b3Z6oT76c6P2w02sS?p=preview

**Comment by Hypocrite** [comment]
That's correct for a normal select box where you only select one option.
But in this case user usually wants to select more than one option so it would be much better if the select box would remain open at least if the multiple attribute is selected.

This was the behaviour in the old oi.multiselect 0.1.7 version we were using and I get feedback from users that they would like to have that back. :)
