### ISSUE TITLE
При открытии выпадающего списка очищается модель.

### ISSUE THREAD

**Issue by grushikhin** [tamtakoe/oi.select#4]
Ситуация:
На директиве висит валидация на заполненость модели.
Выбираю значение из выпадающего списка - модель заполнилась, фокус сбросился.
Повторно кликаю в поле ввода - открывается выпадающий список, но при этом очищается значение модели, и срабатывает валидация. Хотя данные в инпуте не изменились.

**Comment by tamtakoe** [comment]
I fixed it in version 0.2.1

**Comment by grushikhin** [comment]
При редактировании модель все равно очищается.
Нужно добавить опцию, по которой каждый введенный символ будет сразу же попадать в модель

**Comment by orloffv** [comment]
+1

**Comment by isoniko** [comment]
+1
