### ISSUE TITLE
How to remove drop-down options (leave oi-options blank)?

### ISSUE THREAD

**Issue by cklemming** [tamtakoe/oi.select#41]
What would be the best way to only use oi-select for adding new items? I.e. not show the drop-down options at all.

Setting oi-options="null" or "false" clearly does not work.

Making oi.select work with only new items would omit my need to use ng-tags-input.

PS: Thanks for a great project!

**Comment by tamtakoe** [comment]
You can use function which returns empty list http://plnkr.co/edit/LTj8vm5NgYeOKpv22MDL?p=preview
or use same `listFilter`

**Comment by cklemming** [comment]
Thank you, works great. Suppose you can also replace the empty list function with [].
(i.e. oi-options="item for item in []")

**Comment by tamtakoe** [comment]
v. 0.2.13. Add to bower after tests and bug fixes
