### ISSUE TITLE
Save new item on "comma" (saveTrigger)

### ISSUE THREAD

**Issue by cklemming** [tamtakoe/oi.select#43]
Currently it seems only 'enter' and 'blur' are available triggers to save new items. It would be great if new items could be saved on "comma" too.

Will try to build a custom directive for this, but wanted to check if anyone else had a solution already?

**Comment by cklemming** [comment]
I solved it temporarily with the below, not very elegant solution:

```javascript
    element.on('keydown keypress', function(event) {
        // Save new tag with comma or dot
        if( event.which === 44 || event.which === 46) {
            saveOn('enter');
        };
    });
```

**Comment by tamtakoe** [comment]
Good idea. I make this in a future version. I think it will have API `saveTrigger: 'enter blur 44 46'` when you can set any key code

**Comment by cklemming** [comment]
+1

**Comment by phatpham9** [comment]
+1 looking forward to this enhancement

**Comment by tamtakoe** [comment]
v. 0.2.13. Add to bower after tests and bug fixes
