### ISSUE TITLE
Make "multiple" attribute true/false

### ISSUE THREAD

**Issue by cklemming** [tamtakoe/oi.select#48]
It would be extremely useful if the "multiple" attribute could be set dynamically to true or false, so that you could allow users to enable/disable multi select. E.g.

```html
<oi-select
   ng-required="customOption.required"
   multiple="customOption.multiple"
   oi-options="option for option in options track by option"
   ng-model="customOption"
></oi-select>
```

**Comment by tamtakoe** [comment]
I do it if this will not have problems

**Comment by tamtakoe** [comment]
v. 0.2.13. Add to bower after tests and bug fixes
