### ISSUE TITLE
cannot find template

### ISSUE THREAD

**Issue by mrp100461** [tamtakoe/oi.select#50]
Error: [$compile:tpload] Failed to load template: src/template.html

**Comment by tamtakoe** [comment]
@mrp100461 In what situation? Develop, build?

**Comment by mrp100461** [comment]
Found answer had to put path and template in folder and change the template location in the minified file

**Comment by rohitb4** [comment]
I get this error too, not sure why template.html is required

**Comment by bmwertman** [comment]
@mrp100461 you moved the template.html? to which folder? I'm having this same issue

**Comment by ntlzz93** [comment]
@mrp100461 : How to put path and change template location? Explain detail ... please!
