### ISSUE TITLE
Urgent Tabbing away suggestions still showing

### ISSUE THREAD

**Issue by mrp100461** [tamtakoe/oi.select#51]
![test](https://cloud.githubusercontent.com/assets/14923241/10242619/ff89cd56-68e9-11e5-8b24-d87708444167.png)
When I tab away after  adding a new item it still shows .
Here is my code
<oi-select oi-options="o.id as o.description for o in model.availableNames"
ng-model="mar.nameId"
oi-select-options="{
newItem: 'prompt',
newItemFn: 'addName($query)',
saveTrigger: 'blur'
}"
placeholder="Select"></oi-select>

$scope.addName = function (query) {
if (query && _.findIndex(scope.model.availableNamess, { description: query }) === -1) {
$scope.model.name = query;
return resource.addname($stateParams, $scope.model);
}
};
I have now change so only return one item but does not update list where as when I did not return and added item into list and it stayed in the box.

**Comment by tamtakoe** [comment]
try v. 0.2.13

**Comment by mrp100461** [comment]
its ok I got it to work today by returning an object when the object existed
