### ISSUE TITLE
Removing all items in ng-model causes select box to shrink in height

### ISSUE THREAD

**Issue by nitzo** [tamtakoe/oi.select#57]

**Comment by tamtakoe** [comment]
I can not repeat. In what case is this happening? Make example please http://plnkr.co/edit/LnntLUdrAfz0DDlCGtGv?p=preview

**Comment by nitzo** [comment]
Hi,
I traced it down to disabling the select box (via ng-disabled), emptying the content (ng-model) and the re-enabling the select box. 
I do this since I have an API call that I am waiting for and during that time I don't want the user to change the selected items.

I created the scenario here:
http://plnkr.co/edit/d2coiPIpLPbqfFnXSag8?p=preview

Thanks!

**Comment by tamtakoe** [comment]
It fixed in v. 0.2.17

**Comment by nitzo** [comment]
Thanks!
