### ISSUE TITLE
LimitTo doesn't work

### ISSUE THREAD

**Issue by vdzundza** [tamtakoe/oi.select#58]
I've filled options with 7 items. But showns only four items. I tried to set LimitTo 6, but it doesn't help me.

**Comment by tamtakoe** [comment]
Limit works correct http://plnkr.co/edit/OYcetkAmDd21zhhToCC9?p=preview

**Comment by vdzundza** [comment]
Works fine

**Comment by ujjwalgarad** [comment]
is there a way to show more items in the drop down. by default the dropdown shows only 4 items..if there are more than 4 items then scroll bar appears..i have a list of 100+ items and i want drop down to open and show 10 items at a time with scroll bar

**Comment by ujjwalgarad** [comment]
turns out i had to change the CSS file and increase the max-height for the dropdown
