### ISSUE TITLE
debounce not working as expected 

### ISSUE THREAD

**Issue by karmeli87** [tamtakoe/oi.select#61]
Great directive! But i have a small issue.

When using the directive this way:

`<oi-select class="form-input" oi-options="item.name for item in someFn($query)" ng-model="somevar" multiple></oi-select>`

The $query is updated with every keystroke, therefore someFn been called with every update.
I would expect that the $query would be updated when there is no input change for a 500ms (default).

**Comment by tamtakoe** [comment]
It fixed in v. 0.2.17
