### ISSUE TITLE
Can't get current item when removing

### ISSUE THREAD

**Issue by Sweet-Bob** [tamtakoe/oi.select#62]
View:

    oi-select(
        oi-options='item.label group by item.category for (key, item) in categories',
        ng-model='$root.filter',
        multiple,
        placeholder='Search',
        oi-select-options="{ newItem: true, newItemFn: 'addItem($query)', removeItemFn: 'removeItem($item)' }"
    )

Controller:

    $scope.removeItem = function(item) {
        console.log('removed!');
        console.log(item);
    };

When i click i get "undefined"
What i do wrong?

Thanx!

**Comment by Sweet-Bob** [comment]
In directives.js file (i do it only for "multiple" select):

    scope.removeItem = function removeItem(position) {
        if (attrs.disabled || multiple && position < 0) return;

        // Added
        if (ctrl.$modelValue.length != 0) {
            removedItem = ctrl.$modelValue[position];
        }

I think removeItem need add various checks. Thanx!

**Comment by tamtakoe** [comment]
It fixed in v. 0.2.17
