### ISSUE TITLE
Set 'maxlength' for input field

### ISSUE THREAD

**Issue by pajtim4** [tamtakoe/oi.select#64]
I would like to set the attribute 'maxlength' like I can do it on input fields so the user cannot add a custom item with more characters than allowed.

**Comment by tamtakoe** [comment]
You can use `newItemFn` with custom filter. See http://tamtakoe.github.io/oi.select/#/select/#validation, second example

**Comment by pajtim4** [comment]
Thank you for your fast reply.

Yes, it would work that way, but this is some kind of validation after leaving the input field.

For a better user experience I would like to simply not let the user write more than x characters into that. I do it this way in all the other input fields.

**Comment by tamtakoe** [comment]
Yes, it is the best user experience. I realize it in the last version

**Comment by tamtakoe** [comment]
added in v 0.2.19. See validate example
