### ISSUE TITLE
Search filter case sensitivity

### ISSUE THREAD

**Issue by TakaharaShujin** [tamtakoe/oi.select#67]
There are case sensitive in a search term, is there a setting I can change it?
I think this happens only in Turkish characters :(

**Comment by tamtakoe** [comment]
I fixed it in this plunk http://plnkr.co/edit/K9ZtiKmS3E2kjaewfXch?p=preview. Try it.

You can use oiSelectAscSort filter from this plunk in your project or wait some time until I publish new version.

**Comment by tamtakoe** [comment]
It fixed in v. 0.2.21
