### ISSUE TITLE
Add minlength setting

### ISSUE THREAD

**Issue by Hypocrite** [tamtakoe/oi.select#72]
There is at the moment a maxlength option for the input but could you also add a minlength?

I would like to get a similar effect as in here:
http://stackoverflow.com/questions/21012036/how-to-start-filtering-only-when-the-length-of-querytext-is-equal-to-2

So when user inputs something to the field, it would start filtering the list only after user has inputted more than two characters.

Now filtering can be a bit slow if the list is large and filtering starts right after first character.

**Comment by tamtakoe** [comment]
I will add it in new version

**Comment by tamtakoe** [comment]
It added in v. 0.2.21
