### ISSUE TITLE
Sanitize before displaying

### ISSUE THREAD

**Issue by Dalanie** [tamtakoe/oi.select#75]
$scope.bundle = [{
            "id": 5,
            "name": "<b>shirt</b>",
            "category": "clothes"
        },{
            "id": 2,
            "name": "shoes",
            "category": "shoes"
        }];

Will give you a bold-shirt.

You can even create lists and set styles or inject javascript

**Comment by tamtakoe** [comment]
You can sanitize any data in your filter ([example](http://localhost:3000/#/select/#customization)). It is not work of oi.select. Maybe I will use `ng-bind` instead `ng-bind-html` if I rewrite customization part
