### ISSUE TITLE
How can I create infinite scroll loading remote data?

### ISSUE THREAD

**Issue by think2011** [tamtakoe/oi.select#77]
Like https://select2.github.io/examples.html   Loading remote data 

please help me : )

**Comment by tamtakoe** [comment]
You can not use it... Fortunatelly
1. It is difficult task (especially correct working in different browser)
2. It is contrary of idea of autocomplete fields. You have autocomplete, which let you to see small list of actual results. Why you need infinity scroll if you can refine your query string :-)
