### ISSUE TITLE
Required attribute not working.

### ISSUE THREAD

**Issue by theantichris** [tamtakoe/oi.select#78]
`<oi-select oi-options="person.guid as person.name for person in people track by person.guid" ng-model="ngModel" placeholder="Select" multiple="multiple" required></oi-select>`

I have my directive setup like above. The directive's scope does not have the errors object as shown in the demo.

**Comment by tamtakoe** [comment]
Do you have form tag above or ng-if directive? Try it with ng-select

**Comment by theantichris** [comment]
Use ng-select instead of oi-options?

**Comment by theantichris** [comment]
Using a <select> tag with ng-options does work with required. That won't work for me since I need the typeahead.

Here is my full directive.

```
<div class="form-group LdapSelect">
    <label class="control-label" ng-class="required ? 'required' : ''">{{ label }}</label>
    <oi-select oi-options="person.guid as person.name for person in people track by person.guid" ng-model="ngModel" placeholder="Select An Associate" oi-select-options="{cleanModel: true}" required></oi-select>
</div>
```

**Comment by theantichris** [comment]
Looking at the code it doesn't look like you have added support to make the field required.

**Comment by bhaveshvyas007** [comment]
Confirmed, required is not working

**Comment by bhaveshvyas007** [comment]
Even a simple example doesn't work... I am using Angular 1.6.2
