### ISSUE TITLE
'watch' doesn't work when value is an array

### ISSUE THREAD

**Issue by zolototrubova** [tamtakoe/oi.select#81]
when value is an array, watch considers newValue equal to oldValue even if it's array.length has been changed, because array's reference does not change.
if we use parameter 'true', then it will work fine.

**Comment by tamtakoe** [comment]
It is correct behaviour of watch. Angular is not React with immutable paradigm. It is OK if you work with original object and pass it by reference. Deep watch (with `true` parameter) - good descision in this situation.
