### ISSUE TITLE
iOS Keyboard Next/Prev Buttons ignores oi.select fields

### ISSUE THREAD

**Issue by cklemming** [tamtakoe/oi.select#91]
iOS (and possibly on Android) does not seem to consider an `oi.select` field fully part of a form.

The `next/prev field buttons` (equivalent to Tab on desktop) jumps over the oi.select field and focuses on the field after it. Where the next field is oi.select the next button greys out, see below:
![oiselect-ios](https://cloud.githubusercontent.com/assets/10369142/15523191/92289af6-21cd-11e6-8e67-217bfc097d14.png)

Any clue why this is happening and how it can be resolved? User experience on iOS is suffering a bit.

**Comment by tamtakoe** [comment]
Hmm. It works on my iPhone. Try [this example](https://tamtakoe.github.io/oi.select/#/select/#autofocus)
Maybe you didn't set tabindex?

**Comment by cklemming** [comment]
Sorry for the late response. Agree it seems to work with `tabindex`, I created a [plnkr here](http://plnkr.co/edit/lCT2mKVWGr5106FPAp0L?p=preview) to prove that it works too.

However, for some reason, I cannot get this to work in my application. It may be that the form fields are displayed dynamically (with `ng-if`) and that interferes with `tabindex` somehow. I will continue investigating and re-open this if I find the rootcause.
