### ISSUE TITLE
Is there a way to programmatically remove a selection?

### ISSUE THREAD

**Issue by nkesar** [tamtakoe/oi.select#98]
Hi guys.

Is there a way to programmatically remove a selected item from the multiple combo box? I tried removing it from the model but it doesn't seem to work

Thanks
Nikhil

**Comment by kh411d** [comment]
Mine too have this issue, ng-model seems doesn't bind, oi.select version 0.2.21

**Comment by nkesar** [comment]
Thanks @adlh -  assigning it a new object worked.
